### ISSUE TITLE
Parent node is busy

### ISSUE THREAD

**Issue by stats** [KoBeWi/Godot-Universal-Fade#1]
I tried using the 1.1 branch of this and got an error when adding this into the _ready() function of my first scene.

`Fade.fade_out(2, Color.BLACK, "Diamond", false, false)`

```
E 0:00:00:0825   _ready: Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead.
  <C++ Error>    Condition "data.blocked > 0" is true.
  <C++ Source>   scene/main/node.cpp:1135 @ add_child()
  <Stack Trace>  Fade.gd:48 @ _create_fader()
                 Fade.gd:9 @ fade_out()
                 TitleScene.gd:23 @ _ready()
```

**Comment by KoBeWi** [comment]
I think this might happen when you try to fade before any scene is loaded yet (i.e. right at the launch of the project). Try waiting one frame.

**Comment by KoBeWi** [comment]
I clarified that in the readme. This is literally the only case where the fading can fail, so it's not worth any more fixes.
