### ISSUE TITLE
Add more patterns

### ISSUE THREAD

**Issue by univeous** [KoBeWi/Godot-Universal-Fade#4]
I found there are several useful patterns [here](https://github.com/maktoobgar/scene_manager/tree/main/addons/scene_manager/shader_patterns).
Would you like to add them to this repo?
There are some duplicates and textures there are not 1920x1080, but I think it's ok?

**Comment by univeous** [comment]
Also, I found [this website](https://4you.bz/rule1080p) with TONS (300+) of patterns. These textures need credit so maybe it's not a good idea to put them in this repo, but I will leave the website here in case anyone is interested ;)

**Comment by KoBeWi** [comment]
I have myself a collection of 500+ patterns gathered from various RPG Maker sites 🤔
I wonder if it's better to include the patterns you mentioned or just link to them in the README. I could just add new patterns infinitely, but in practice only 1 or 2 are used in a single project, so it's just a download bloat.

**Comment by univeous** [comment]
I agree that it might not be a good idea to add too many patterns here. It's totally fine to link them in the README.
The real problem is that I'm using [gd-plug](https://github.com/imjp94/gd-plug) to manage addons, so I don't include them in VCS and therefore I don't want to make any changes to addons. If an extra pattern path can be configured outside the addon, and the addon can get patterns from the built-in path and the extra path, then everything would be fine for me. Maybe save it in the project settings?

**Comment by KoBeWi** [comment]
Yeah I could add a project setting.

**Comment by KoBeWi** [comment]
Ok, sorry for waiting. In 3de001fc93520412f25970e456bda3574ffcbef5 I added Radial pattern and added links with more patterns to the README. In c4bbdc69f43a69fe455b20722c8f8dc5d0bedb8d I added a project setting: `addons/UniversalFade/patterns_directory`.
