### ISSUE TITLE
await Fade.fade_out().finished fades out twice

### ISSUE THREAD

**Issue by scarzehd** [KoBeWi/Godot-Universal-Fade#6]
I'm not entirely sure what's causing this, but when I use the above line of code, the screen fades, snaps back to full visibility, then fades back out. Then, it waits a bit and fades back in. This only seems to happen when I add a new node after the screen finishes fading out.

Here's the relevant code: 

```
func change_level(scene_path):
	await Fade.fade_out().finished
	
	call_deferred("_deferred_change_level", scene_path)

func _deferred_change_level(scene_path):
	current_level.free()
	current_level = load(scene_path).instantiate()
	$"/root/Main".add_child(current_level)
	$"/root/Main".move_child(current_level, 0)
	
	Fade.fade_in()
```

**Comment by KoBeWi** [comment]
My guess would be that `change_level()` is somehow called twice. You could put a breakpoint inside `fade_out()` to see where is it called from.

**Comment by scarzehd** [comment]
Yep, it certainly looks like it's being called twice. It seems like there isn't any issue with the addon, so I'll close the issue.
