### ISSUE TITLE
await Fade_in/out() makes the addon ignore any parameters

### ISSUE THREAD

**Issue by smolsosig** [KoBeWi/Godot-Universal-Fade#7]
Using Godot v4.2.1.stable.official.b09f793f5.

`Fade.fade_in(1, Color.WHITE, "Diagonal")`, for example, works fine on its own. The problem comes when you add `await Fade.fade_in().finished` on the next line. It immediately defaults to, well, the default parameters when you add it.

https://github.com/KoBeWi/Godot-Universal-Fade/assets/110701935/b933e933-f8f2-45dc-a1c8-450090b9a3f9

The same applies to `Fade.fade_out()` of course.

It sucks, the only workaround I can think of for it is to have a oneshot timer that starts alongside the Fade, and emits a `timer_stopped` signal around the same time as it ends, but I don't want to keep doing that when I use this addon a lot.

**Comment by KoBeWi** [comment]
Your code is wrong, it should be `await Fade.fade_in(1, Color.WHITE, "Diagonal").finished` without the second line.

**Comment by smolsosig** [comment]
AH my mistake, thanks!
